### ISSUE TITLE
Add social media handles

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#12]
- Add Instagram, LinkedIn, dev.to, and GitHub icons at the extreme right of the navbar 
- Something like this
![image](https://user-images.githubusercontent.com/89704304/196896916-095f1436-f68f-487b-b1e7-865c9c0515b5.png)
- Make sure that the icon is an SVG and not an image and its width and height should be equal to 24*24 px.
- Add links to the icons
- **Instagram** https://instagram.com/kya.bne.ga.burhan.tera
- **Linkedin** https://linkedin.com/burhandev
- **dev.to** https://dev.to/burhanharoon
- **GitHub** https://github.com/burhanharoon

Happy Hacking!

**Comment by idrismusa4** [comment]
Can fontawesome icons be used?

**Comment by avezqureshi14** [comment]
Hello @burhanharoon bro can you assign this to me, I will complete the task in the best way and make the pull request in just few minutes as soon as you assign this issue to me

**Comment by burhanharoon** [comment]
Yeah sure. Thanks.

**Comment by burhanharoon** [comment]
@idrismusa4 No please.

**Comment by avezqureshi14** [comment]
@burhanharoon bro should I keep the Contact Me or should it be replaced by this icons

**Comment by burhanharoon** [comment]
No, please keep the contact me button. I will redirect to a contact page in the future.

**Comment by Vishesh-Vijay** [comment]
pls assign this to me

**Comment by avezqureshi14** [comment]
Ok @burhanharoon bro

**Comment by avezqureshi14** [comment]
Bro Just Now I made the PULL request, Please Review it

**Comment by burhanharoon** [comment]
@avezqureshi14  Awesome work.
