### ISSUE TITLE
The icons in the navbar are very big.

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#14]
The website looks very good, but we still need the following changes:

- Please resize the icons to have 24px width and height.
- In the mobile navbar, the icons are displayed vertically. Can you please make them horizontal with justify-between flex property? So they are spaced correctly.
- On big screens, the navbar links are very close to the icons. Can you apply the same justify-between flex property so that the title, navbar, and icons are spaced correctly?

Thanks!

**Comment by BGS89** [comment]
@burhanharoon I would like to do this. Please assign me : )

**Comment by burhanharoon** [comment]
Yeah, sure @BGS89 . Here you go!

**Comment by burhanharoon** [comment]
@BGS89 Please make sure to use Tailwind-CSS to do any CSS changes. That would be perfect. Thanks.

**Comment by BGS89** [comment]
@burhanharoon very sorry I won't be able to complete this in good time so have unassigned myself so that somebody else can complete the task for you.

**Comment by burhanharoon** [comment]
Sure. No worries!

**Comment by avezqureshi14** [comment]
Can you assign me this  back, I didn't knew that you will face this problem
