### ISSUE TITLE
prettier config file

### ISSUE THREAD

**Issue by Shubhamsahu19** [burhanharoon/next-portfolio#15]
everyone uses prettier code formatter , so everyone has different global prettier configuration, which leads to multiple unnecessary changes in file. So having a local `prettierrc` and `prettierignore` can eliminate these unnecessary changes.

**Comment by burhanharoon** [comment]
That sounds very good. Do you want to contribute to that? @Shubhamsahu19

**Comment by Shubhamsahu19** [comment]
Okk i will do it.

**Comment by burhanharoon** [comment]
Ok I'm assigning this to you. Thanks.
