### ISSUE TITLE
Make navbar display on all pages.

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#19]
Right now the navbar is displayed explicitly on the '/' page.  We want the navbar to be displayed on every other page (there are no other pages, but will be added in the future) without explicitly declaring its component on every new page. Thanks.

**Comment by nirajpdn** [comment]
I want to do this. Assign this to me

**Comment by burhanharoon** [comment]
@nirajpdn do you understand what to do?

**Comment by nirajpdn** [comment]
> @nirajpdn do you understand what to do?

yeah

**Comment by burhanharoon** [comment]
Go ahead. Best of luck.

**Comment by burhanharoon** [comment]
Thanks, @nirajpdn for the contribution. I wish you the best of luck in your future endeavors.
