### ISSUE TITLE
[BUG] : Footer doesn't stick at bottom.

### ISSUE THREAD

**Issue by nirajpdn** [burhanharoon/next-portfolio#21]
## Description
Footer is floating and it must be stick always at the bottom of the page even if there is no content in the page.

<img width="909" alt="Screen Shot 2022-10-26 at 06 40 35" src="https://user-images.githubusercontent.com/59108522/197917884-4ecaff2e-3a64-43e5-bffa-3408c16603bb.png">

**Comment by JawHawk** [comment]
I can do this, pls assign it to me

**Comment by burhanharoon** [comment]
Sure @JawHawk

**Comment by nirajpdn** [comment]
I want to do this.

**Comment by burhanharoon** [comment]
Yeah sure @nirajpdn. Here you go!
