### ISSUE TITLE
Add contributors photo in README.md

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#23]
I wanted to thank all the contributors to this repository by displaying them in my repo's readme file. I'm expecting something like this (picture below) in my readme. If you can do this, then please comment. Thanks.

![image](https://user-images.githubusercontent.com/89704304/198060643-72c1d55b-bcab-4953-a236-108af9550e64.png)

**Comment by Rohit-R2000** [comment]
Please assign this to me

**Comment by burhanharoon** [comment]
@Rohit-R2000 sure.

**Comment by singhkaran202** [comment]
Hello @burhanharoon, I'd love to work on this.
Can you please assign this to me?

**Comment by burhanharoon** [comment]
@singhkaran202 sorry mate but this has already been completed by @Rohit-R2000.
