### ISSUE TITLE
Make the Navbar Sticky.

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#4]
The navbar currently isn't sticky. Now, it disappears whenever we scroll. Can anyone please make the header sticky so it always stays at the top of the website?

**Comment by YajanaRao** [comment]
@burhanharoon Let me give this a try today ?

**Comment by burhanharoon** [comment]
Yeah sure. I'm assigning it to you. Good Luck @YajanaRao !

**Comment by YajanaRao** [comment]
@burhanharoon The navbar will be fixed at the top now.
![sticky-navbar](https://user-images.githubusercontent.com/38914337/196466723-f0ec4c1b-44ba-46be-b266-947bbad1de74.gif)

What would be the background color of navbar ?

**Comment by burhanharoon** [comment]
It looks awesome. Great work. Can you make the header have the same bg color at top but when the page is scrolled it changes it bg color to white and when it is scrolled back to top, the color is changed back to the original? That would be too awesome!

**Comment by YajanaRao** [comment]
@burhanharoon  This scroll can be seen on mobile the best:

![navbar-scroll-color-change](https://user-images.githubusercontent.com/38914337/196482172-29643610-fb27-4e25-b534-31a778fed6dc.gif)
