### ISSUE TITLE
Add footer at the bottom.

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#5]
Currently, there is no footer on the website. I have the required design, can someone please create a responsive footer?

Footer on small screens (below 600px): 
![image](https://user-images.githubusercontent.com/89704304/196464083-82af09b9-132d-492f-aca0-673aced33cb5.png)

Footer on medium screens (anywhere between 600px to 1000px)
![image](https://user-images.githubusercontent.com/89704304/196464412-ef94062e-7ad2-4e6b-bc3d-fdcfa420d810.png)

Footer on large screens:
![image](https://user-images.githubusercontent.com/89704304/196464661-3b4a62c9-8b24-4cec-81d4-6e83877cd776.png)

Please use Tailwind CSS to and its breakpoints design the footer component and then make it responsive. Thanks.

**Comment by shrutilenka** [comment]
Hey @burhanharoon , I am interested to work on this issue.So could you please assign this to me?

**Comment by HydraPhyzer** [comment]
Hey @burhanharoon , I am interested in fixing this issue regarding Footer. It Would be a Great Help if you could assign it to me.

**Comment by GloriaOkeke** [comment]
Hey @burhanharoon , I will like to work on this. Please could you assign to me?

**Comment by burhanharoon** [comment]
Hello, everyone, I looked at your profiles and I found @HydraPhyzer with some experience in tailwind CSS. So, I'm assigning this to him. Keep contributing to open-source and I wish y'all the best of luck.

**Comment by HydraPhyzer** [comment]
> Hello, everyone, I looked at your profiles and I found @HydraPhyzer with some experience in tailwind CSS. So, I'm assigning this to him. Keep contributing to open-source and wish y'all the best of luck.

Thank you so much sir, I am Working on it

**Comment by GloriaOkeke** [comment]
Thank you @burhanharoon

**Comment by HydraPhyzer** [comment]
Hey @burhanharoon, Could Please Check the Pull Request for My Recent Changes (Addition of Footer, etc) that I Have Made?

**Comment by burhanharoon** [comment]
@HydraPhyzer Thanks for the contribution. This issue is solved and hence is being closed now.
