### ISSUE TITLE
The mobile navbar doesn't work.

### ISSUE THREAD

**Issue by burhanharoon** [burhanharoon/next-portfolio#8]
**Current Behaviour:**
The navbar doesn't work on clicking on the hamburger icon in the mobile view.

![image](https://user-images.githubusercontent.com/89704304/196488483-41f2ac34-f0cd-41c5-aaf6-8e8fcc84320a.png)

**Expected Behaviour:**
The navbar should open/extend. I have the design. The navbar menu should look like this: 

![image](https://user-images.githubusercontent.com/89704304/196489133-baec129f-d6a4-40e6-a214-179cc51128e6.png)

**Note: Please use Tailwind-CSS to accomplish the task (if you can).**

**Comment by stevenjburrows** [comment]
I can work on this for you if you assign me

**Comment by burhanharoon** [comment]
Yeah sure. Here you go!

**Comment by stevenjburrows** [comment]
Do you want it coded with just tailwind or would you like it to also use headlessui by tailwind

**Comment by burhanharoon** [comment]
Nope! Just the tailwind please.

**Comment by burhanharoon** [comment]
Hy, what's the status @stevenjburrows ?

**Comment by stevenjburrows** [comment]
I will be starting to work on this shortly

**Comment by burhanharoon** [comment]
Great! Keep me updated.
